#!/bin/bash

echo "Supabase Setup Script for NanoBanana Backend"
echo "============================================"
echo ""
echo "Prerequisites:"
echo "1. Create a Supabase project at https://supabase.com"
echo "2. Have your project URL and keys ready"
echo ""
echo "Steps to complete:"
echo ""
echo "1. Create Storage Buckets:"
echo "   - Go to Storage in Supabase dashboard"
echo "   - Create bucket 'images' (public)"
echo "   - Create bucket 'user-uploads' (public)"
echo ""
echo "2. Run Database Schema:"
echo "   - Go to SQL Editor in Supabase dashboard"
echo "   - Copy and run the contents of supabase/schema.sql"
echo ""
echo "3. Configure Environment Variables:"
echo "   - Copy .env.example to .env.local"
echo "   - Fill in your Supabase credentials:"
echo "     * NEXT_PUBLIC_SUPABASE_URL"
echo "     * NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "     * SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "4. Enable Apple Authentication (optional):"
echo "   - Go to Authentication > Providers"
echo "   - Enable Apple provider"
echo "   - Configure with your Apple credentials"
echo ""
echo "5. Set up Row Level Security (RLS):"
echo "   - The schema.sql already includes RLS policies"
echo "   - Verify they are enabled in the dashboard"
echo ""
echo "Press Enter to continue..."
read

echo "Opening Supabase dashboard..."
open "https://supabase.com/dashboard"

echo ""
echo "Setup checklist:"
echo "[ ] Created Supabase project"
echo "[ ] Created storage buckets (images, user-uploads)"
echo "[ ] Ran database schema"
echo "[ ] Configured environment variables"
echo "[ ] Tested database connection with npm run dev"
echo ""
echo "Done! Your Supabase backend is ready."